Adds support for FILE_DIR
monster860/FastDMM pull request #20
Opened 2016-09-30 20:31 UTC by PJB3005

Fixes #17

2016-09-30 21:08 UTC, ghost requested changes
👎

2016-09-30 21:08 UTC, ghost commented on src/main/java/com/github/monster860/fastdmm/FastDMM.java
> +					                       objTree.filePath(Util.separatorsToSystem(name))));
Please don't do this.

2016-09-30 21:08 UTC, ghost commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTreeParser.java
> +							Matcher quotes = Pattern.compile("^\"(.*)\"$").matcher(m.group(2));
Please use `CachedPattern.java` instead of creating a new pattern each time.

2016-09-30 21:08 UTC, Chnkr commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTree.java
> +			if(newFile.exists() && newFile.canRead())
Please add braces around if statements

2016-09-30 21:08 UTC, Chnkr commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTree.java
> +	public LinkedList<Path> fileDirs = new LinkedList<Path>();
Change this to `public LinkedList<Path> fileDirs = new LinkedList<>();`

2016-09-30 21:11 UTC, ghost requested changes

2016-09-30 21:11 UTC, Chnkr commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTree.java
> +		for(Iterator<Path> i = fileDirs.iterator(); i.hasNext();) {
There is no need to use `iterator()` here, doing `for (Thing t : things) {}` would be cleaner

2016-09-30 23:45 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTree.java
> +		for(Iterator<Path> i = fileDirs.iterator(); i.hasNext();) {
Stackoverflow lied to me then.

2016-09-30 23:45 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/FastDMM.java
> +					                       objTree.filePath(Util.separatorsToSystem(name))));
What exactly is wrong with this?

2016-10-01 09:32 UTC, Chnkr commented on src/main/java/com/github/monster860/fastdmm/FastDMM.java
> +					                       objTree.filePath(Util.separatorsToSystem(name))));
There is no need to break up long lines, it only clutters things.

2016-10-01 10:26 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/FastDMM.java
> +					                       objTree.filePath(Util.separatorsToSystem(name))));
Really this is a discussion for coding styles which we haven't established (I've seen mixed types of `if (` and `if(`

2016-10-01 11:33 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTreeParser.java
> +							Matcher quotes = Pattern.compile("^\"(.*)\"$").matcher(m.group(2));
Where would I find the documentation on this?

2016-10-01 11:38 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTreeParser.java
> +							Matcher quotes = Pattern.compile("^\"(.*)\"$").matcher(m.group(2));
Oh never mind that's something in FastDMM itself, surprisingly google ended up at that.

2016-10-01 12:01 UTC, PJB3005 commented
Alright, should be good now.

2016-10-01 13:13 UTC, Chnkr commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTreeParser.java
> +    public static final CachedPattern quotesPattern = new CachedPattern("^\"(.*)\"$");
This is only used within this class, no need to define it as `public static` also `final` modifiers should have it's variable named as `FULLCAPS`.

I'd suggest changing this to `private final CachedPattern QUOTES_PATTERN = new CachedPattern("^\"(.*)\"$");`

2016-10-01 13:14 UTC, ghost approved these changes

2016-10-01 13:26 UTC, PJB3005 commented on src/main/java/com/github/monster860/fastdmm/objtree/ObjectTreeParser.java
> +    public static final CachedPattern quotesPattern = new CachedPattern("^\"(.*)\"$");
Alright

2016-10-01 14:33 UTC, merged

2016-10-01 14:50 UTC, PJB3005 commented
... I didn't actually rename that variable yet.