Added rudimentary undo/redo functionality
monster860/FastDMM pull request #40
Opened 2017-03-26 21:08 UTC by Cruix

Closes #38 

Added undo and redo for the following operations:
* Placing an atom/atoms
* Deleting an atom/atoms
* Editing the variables of an atom
* Moving an atom to the top/bottom of the tile
* Moving a selection
* Deleting a selection
* Pasting a selection

At the moment, moving a selection is considered two operations: pasting the selection to the new place, and removing it from the old place.

The only way to use undo and redo is to use the dropdown menu. No hotkeys yet.

2017-03-26 22:26 UTC, Qustinnus commented
you are a god.

2017-03-26 22:36 UTC, monster860 requested changes
I feel like there's a simpler way to do this:

- Keep an archived copy of the tile instance list and the position-key table
- Have a "push" method that compares the archived copy to the current and records the changes and makes the archived equal to the current

Sure, it uses a bit of extra memory but it's not like we don't have a fuckton of it, but it makes coding for it as simple as doing a push when you're done..

2017-03-26 22:46 UTC, Cruix commented
You mean keeping a copy of the entire map for every single change that is made? That seems a bit excessive.

2017-03-26 22:53 UTC, monster860 commented
No, keeping only the changes to the map (location (1,1) used to point to "aa" now it points to "bb") and the meanings of the keys referenced before and after the change.

2017-03-27 04:50 UTC, bauen1 commented
```
Sure, it uses a bit of extra memory but it's not like we don't have a fuckton of it
```
And thats how bloatware happens.

Keeping a copy of the entire map will make its a memory gun and make it slow, how about a diff for each action instead ?

2017-03-27 12:54 UTC, monster860 commented
> how about a diff for each action instead ?

That is literally what I've been suggesting the whole time.....

2017-05-25 23:13 UTC, Iamgoofball commented
@monster860 @Cruix can you guys do this

2017-05-26 23:15 UTC, monster860 commented
I don't like the way this change is implemented.

2017-06-22 23:42 UTC, Cruix commented
Leave a comment

2017-06-22 23:42 UTC, closed without merging